
name: Generate data
on:
  push:
    paths:
      - 'data/**.md'

jobs:
  build:
    name: Generate data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Generate data by the script
        run: python3 ./tools/generate.py
      - name: Commit files
        run: |
          git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --local user.name "${GITHUB_ACTOR}"
          git commit -a -m "Fixed generated data"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ env.TOKEN }}
